# https://cert-manager.io/docs/configuration/acme/
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
  namespace: cert-manager
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    preferredChain: "ISRG Root X1"
    privateKeySecretRef:
      name: letsencrypt-issuer-account-key
    solvers:
    - dns01:
        cloudflare:
          email: glazu@pivotal.io
          apiKeySecretRef:
            name: cloudflare
            key: global_api_key
      selector:
        dnsNames:
        - 'tgir-s01e08-bugs.rabbitmq.com'
        - 'tgir-s01e08-bunny.rabbitmq.com'
