apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: rabbitmq-bunny-ca
spec:
  ca:
    secretName: rabbitmq-bunny-ca
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: rabbitmq-bunny-cert
spec:
  secretName: rabbitmq-bunny-tls
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  subject:
    organizations:
    - RabbitMQ
  commonName: rabbitmq-bunny-tls
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - server auth
    - client auth
  dnsNames:
  - "*"
  - "*.default"
  - tgir-s01e08-bunny.rabbitmq.com
  issuerRef:
    name: rabbitmq-bunny-ca
    kind: Issuer
    group: cert-manager.io