apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: rabbitmq-bunny-cert
spec:
  secretName: rabbitmq-bunny-tls
  dnsNames:
  - tgir-s01e08-bunny.rabbitmq.com
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
    group: cert-manager.io
