apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: rabbitmq-bugs-cert
spec:
  secretName: rabbitmq-bugs-tls
  dnsNames:
  - tgir-s01e08-bugs.rabbitmq.com
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
    group: cert-manager.io
